### PR TITLE
Added Vimeo Player and removed symlinks

### PR DESCRIPTION
**Pull request by smntb**
The Merge Request includes

Add Soundcloud to viewer config file
Add Vimeo as option for Viewer
Change "funding" field to "Acknowledgement" and add to OHMS viewer footer
Minor fixes in youtube
Removed the symlink files from the code, now it will have the viewer.php

### CODE REVIEW

**Comment by cokernel** [comment]
@smntb , this removes index.php and render.php, potentially breaking published URLs.  I can't merge this as is.

**Comment by smntb** [comment]
some people were having an issue, when they clone the code they symlink files does not work for them. I checked the code and there is no instance of index.php and render.php in the code, but yes it can still break the application if people are using those links

Another solution is, to copy the viewer.php and create index.php and render.php

Let us know what you think and we will adjust accordingly.

Thanks

**Comment by cokernel** [comment]
@smntb, yes, historically the default viewer URL was render.php, and this is what is used by the home instance.  I haven't seen viewer.php in the wild but I see that that is what the README recommends.  The symlinks were originally introduced to allow viewer.php to work.  (This ought to work on Linux systems, the main initial target.)

What do you think about a pre-commit hook which copies the contents of viewer.php to index.php and render.php?  This would allow edits to be made to one file, avoid symlinks, and avoid the need to change published URLs.

**Comment by smntb** [comment]
We can write a hook, but we cannot push a hook to git repo. We can write a setup.sh file that will create the missing files, and we can update or documentation as well. 

Let me know what you think?

**Comment by cokernel** [comment]
@smntb , in the short term (to get the Vimeo support into our testing environment soon), I'll merge your current changes but just do a by-hand copy of the files.  I want to investigate the possibilities with hooks a bit more before asking for a setup.sh file.

**Pull request merged**
